-- Update case status enum
ALTER TABLE cases DROP CONSTRAINT IF EXISTS cases_status_check;
ALTER TABLE cases ADD CONSTRAINT cases_status_check CHECK (status IN ('NEW', 'ALLOCATED', 'VISIT_STARTED', 'FORM_SUBMITTED', 'ADMIN_REVIEW', 'REPORT_GENERATED', 'SUBMITTED_TO_BANK', 'COMPLETED', 'REJECTED'));
